branch-defaults:
  master:
    environment: fast-dev
environment-defaults:
  fast-dev:
    branch: master
    repository: origin
global:
  application_name: fast
  default_ec2_keyname: null
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
