# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 169ce8e385533917506912e02ca5650f821bfeda435132edfb5f8a6874869e01acc2b93b59b2cdb9e6115b427a6b795184a39e014dd0c848f1a099fd84e0fb04

test:
  secret_key_base: 4097b8dedb9e8430558042b248b332422a0392ef5e4f9d4645a175a92d64520a3f1dcb28e68911a3a6f04133b0cd4acbc6ca1dfec0efbc3b6b20bab307172528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 033edd7a809e155a55ee33c8c6a568e2b82402d0750b2521b474a25f1e2d13a4ddf52346edc7eb635d73f0f4dee2625d94dd505582603d5c14a88e45fac05aba
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
